---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: appns
  labels:
    app: app
spec:
  containers:
  - name: app
    image: registry.local:5000/library/app-boot:1.0.0
    resources:
      requests:
        memory: "128Mi" # Mi, M
        cpu: "500m" # m milli-cpu
      limits:
        memory: "256Mi" # Mi, M
        cpu: "500m" # m milli-cpu
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: appns
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - port: 8080
    targetPort: 8080
  