apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: appns
spec:
  containers:
  - image: docker.io/library/nginx
    name: nginx
    ports:
      - containerPort: 80
  restartPolicy: Always
