apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  namespace: appns
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            memory: "128Mi" # Mi, M
            cpu: "500m" # m milli-cpu
          limits:
            memory: "256Mi" # Mi, M
            cpu: "500m" # m milli-cpu
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: appns
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - port: 8080
    targetPort: 80

